"""Version stamp.

This file is regenerated by the release CI from the `v*` git tag being
built (see .github/workflows/release.yml). The value below is the
fallback used for local/source-tree runs and pip installs where no tag
was stamped in.
"""
__version__ = "0.0.0-dev"
